### PR TITLE
Fix for multichain network

### LINKED ISSUE #2294: Debug the gov update-client command
For some reason this command is failing on TestNet and locally. Figure out why and fix.

### LINKED ISSUE #2299: When we upgrade to SDK 0.44.3 upgrade ibc-go to v2.0.2
There is a breaking change in there we want to pick up that fixes a bug. The bug requires extra arguments to be passed when someone creates a new proposal to upgrade the chain.

### PR DESCRIPTION
**Pull request by brianosaurus**
This PR

- [x] Fixes scripts/init-multichain.sh to run properly
- [x] Adds hermes instead of the older typescript relayer
- [x] Fixes scripts/run-multichain.sh to run properly
- [x] Upgrades ibc-go to v2@2.0.2 to get a bugfix
- [x] Keeps the chain on cosmos-sdk 0.43 however also (once we change that) leaves us on cosmos-sdk 0.44.5

Closes #2294 
Closes #2299

### CODE REVIEW

**Comment by timlind** [comment]
@Jedi2002 can you review?

File: scripts/vote.sh [hunk 1]
```diff
@@ -0,0 +1,10 @@
+#!/bin/zsh
+
+echo "vote for $1"
```
Comment (Jedi2002) [inline scripts/vote.sh:3]: Is this a seperate requirement ?

File: scripts/run-multichain.sh [hunk 2]
```diff
@@ -1,29 +1,17 @@
...
-#Reset connections
-ibc-setup ics20 --mnemonic "race draft rival universe maid cheese steel logic crowd fork comic easy truth drift tomorrow eye buddy head time cash swing swift midnight borrow" --home ~/.ibc-122
-ibc-setup ics20 --mnemonic "race draft rival universe maid cheese steel logic crowd fork comic easy truth drift tomorrow eye buddy head time cash swing swift midnight borrow" --home ~/.ibc-31
-ibc-relayer start -i -v --poll 10 --home ~/.ibc-122
-ibc-relayer start -i -v --poll 10 --home ~/.ibc-23
-ibc-relayer start -i -v --poll 10 --home ~/.ibc-31
-#Created channel:
-#  localnet-1: transfer/channel-0 (connection-0)
-#  localnet-2: transfer/channel-0 (connection-0)
+echo "starting sifnode servers"
```
Comment (Jedi2002) [inline scripts/run-multichain.sh:8]: Do you think it would make sense to add a gaia network here as well ? The steps can be pretty much identical , and it would help us test more scenarios

**Comment by intl-man** [comment]
@brianosaurus - we should increment the version in `/version` as well as adjust `app/setup_handlers.go`.

**Review by timlind — APPROVED** [review]

File: scripts/vote.sh (hunk 1 above)
Comment (brianosaurus) [reply scripts/vote.sh:3]: It is part of the overall system used to test the fixes. Nor necessarily part of sifnoded on DevNet, TestNet, MainNet however locally used to see things working.

File: scripts/run-multichain.sh (hunk 2 above)
Comment (brianosaurus) [reply scripts/run-multichain.sh:8]: I guess I'd have to say that, in the interest of time, less is more.

**Review by intl-man — APPROVED** [review]
